my_string = input('Введите произвольный текст: ')
print('Количество символов введенного текста составляет:', len(my_string))
print('Строка в верхнем регистре:', my_string.upper())
print('Строка в нижнем регистре:', my_string.lower())
print('Строка без пробелов:', my_string.replace(' ', ''))
print('Последний символ строки:', my_string[-1])
